### ISSUE TITLE
File exclude list does not work from different working directory

### ISSUE THREAD

**Issue by FlixCoder** [crate-ci/typos#901] opened 2024-01-08 15:12 UTC
Hi,

I just noticed that `files.extend-exclude` does not work properly in the `.typos.toml` file, when a different working directory is used. It only happens if a sub-folder is mentioned in the exclude pattern, so the following steps to reproduce:

1. There is a file `./tests/bla.crt` which has multiple recognized typos.
2. In `./.typos.toml` there is `tests/bla.crt` as exclude pattern.
3. Now invoke `typos` in the current directory and it works.
4. Now invoke `typos ./foo` in the parent directory and it fails.

**Comment by epage** [comment] 2024-01-08 15:24
This looks to be a duplicate of #593.  If I missed something and we need to keep this separate issue open instead, let us know!

**Closed by epage** 2024-01-08 15:24 UTC

**Comment by FlixCoder** [comment] 2024-01-08 15:26
Whoops, sorry
