### ISSUE TITLE
False positive caused by `PNGs`

### ISSUE THREAD

**Issue by benegee** [crate-ci/typos#986] opened 2024-04-08 13:12 UTC
In our repository https://github.com/trixi-framework/libtrixi we have doxygen's `Doxyfile` lying around. Since 1.20 we get the following error:

```
error: `PN` should be `ON`
  --> ./docs/doxygen/Doxyfile:1767:71
     |
1767 | # https://inkscape.org)/ to generate formulas as SVG images instead of PNGs for
     |                                                                        ^^

```

**Comment by epage** [comment] 2024-04-09 01:44
Closing as a duplicate of #967

**Closed by epage** 2024-04-09 01:44 UTC
