### ISSUE TITLE
--exclude / extend-exclude does not affect explicitly specified files

### ISSUE THREAD

**Issue by scop** [crate-ci/typos#548] opened 2022-08-31 20:47 UTC
Exclusions specified with --exclude or files.extend-exclude do not seem to affect files explicitly passed as arguments.

```shellsession
$ cat test.txt 
aack
$ typos --format brief
./test.txt:1:0: `aack` -> `ack`
$ typos --format brief --exclude test.txt           # this is ok, test.txt is excluded
$ typos --format brief --exclude test.txt test.txt  # this does _not_ exclude test.txt!
test.txt:1:0: `aack` -> `ack`
```

This is problematic for example with pre-commit, which passes filenames to typos, causing exclusions in .typos.toml and friends or --exclude to not take effect. To work around it, one needs to additionally exclude the files on pre-commit level, but also specify in typos' config to cover direct typos invocations without pre-commit.

**Comment by epage** [comment] 2022-08-31 20:50
This is a duplicate of https://github.com/crate-ci/typos/issues/347

**Closed by epage** 2022-08-31 20:50 UTC
