### ISSUE TITLE
Ignore git directory by default

### ISSUE THREAD

**Issue by szepeviktor** [crate-ci/typos#1012] opened 2024-05-03 18:57 UTC
I always check dot (hidden) files.
Typos works on the filesystem, not on git index, so I have to ignore `.git/` every time.

Please consider always ignoring git directory.

From https://github.com/nushell/nushell/pull/12751/commits/c208b97937b8f73d0bd577560ff0bcbc50f07208

**Comment by epage** [comment] 2024-05-03 22:05
Isn't this a variant of #788?

**Comment by szepeviktor** [comment] 2024-05-03 22:18
No. In #788 I want typos to work on git index.
In this one I want to ignore git dir by default.

**Comment by epage** [comment] 2024-05-03 22:23
In both, the root cause seems to be about wanting to ignore `.git`.  Could you help me understand why you are proposing two separate solutions with separate discussions for the same root problem?

**Comment by szepeviktor** [comment] 2024-05-03 22:51
In #788 I was exploring the possibility of working on git index instead of the filesystem.
In this one I do want to work on the filesystem + hidden files + excluding the git dir.

I hope this makes a difference.

**Comment by epage** [comment] 2024-05-04 09:08
I understand the solutions are different but i was wondering if there are different use cases or are they two solutions to one problem.

Ive found in most cases its best for an issue to be focused on the problem with any solution to be fair game in the same thread. This reduces noise, reduces redundant conversations, and makes it easier to evaluate the solutions against each other.

**Comment by szepeviktor** [comment] 2024-05-04 09:25
Actually both boil down to these two.

1. I don't want typos to select which files are included/excluded, I rather do it myself.
2. I don't want typos to exclude parts of the content, e.g. URL-s

**Comment by epage** [comment] 2024-05-04 10:45
wrt this issue, I'm closing in favor of keeping the conversation centralized in #788

**Closed by epage** 2024-05-04 10:45 UTC
