### ISSUE TITLE
--exclude not working

### ISSUE THREAD

**Issue by m3lab-zzl** [crate-ci/typos#1043] opened 2024-06-21 09:50 UTC
Could you give an example of setting `--exclude` option?

I want to skip typo check for some python files, but
```sh
❯ typos *.py --exclude np2.py
error: `teh` should be `the`
  --> np2.py:7:1
  |
7 | teh = 0
  | ^^^
  |
```

It still checks np2.py.

**Comment by epage** [comment] 2024-06-21 14:26
`--exclude` is a CLI flag for the `files.extend-exclude` field.  In both cases, when you manually specify a file, that is considered a "force" mode and overrides excludes.  You can change this with the `--force-exclude` flag.

As this is working as intended, I'm going to go ahead and close this.  If there is a reason we should reconsider, let us know!

**Closed by epage** 2024-06-21 14:26 UTC

**Comment by m3lab-zzl** [comment] 2024-06-21 15:10
@epage I am not sure why `--force-exclude` has no effect:

<img width="341" alt="image" src="https://github.com/crate-ci/typos/assets/102862066/1408814e-e7f6-49c9-a996-8860ee7b6117">

**Comment by epage** [comment] 2024-06-21 15:12
`--force-exclude` is a flag that modifies the behavior `files.extend-exclude` (and by extension `--exclude`).

So you need to run `typos *.py --force-exclude --exclude new.py`

**Comment by m3lab-zzl** [comment] 2024-06-21 15:36
Thank you. That works.

**Comment by MrXnneHang** [comment] 2024-11-20 01:44
Hello there 
I add `--exclude-force` to my `.pre-commit-config.yaml`

```yaml
  - repo: https://github.com/crate-ci/typos.git
    rev: v1.27.3
    hooks:
      - id: typos
        args: [--force-exclude]
```
It can pass when I run `pre-commit run --all-file`.But when I try to `git commit -m update`,It will send me typo errors.

```shell
(test) xnne@xnne-PC:~/code/yutto-uiya$ pre-commit cleanCleaned /home/xnne/.cache/pre-commit.
(test) xnne@xnne-PC:~/code/yutto-uiya$ pre-commit installpre-commit installed at .git/hooks/pre-commit
(test) xnne@xnne-PC:~/code/yutto-uiya$ pre-commit run --all-file
[INFO] Initializing environment for https://github.com/psf/black-pre-commit-mirror.
[INFO] Initializing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Initializing environment for https://github.com/crate-ci/typos.git.
[INFO] Installing environment for https://github.com/psf/black-pre-commit-mirror.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/crate-ci/typos.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
black....................................................................Passed
ruff.....................................................................Passed
typos....................................................................Passed
(test) xnne@xnne-PC:~/code/yutto-uiya$ git commit -m update[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/xnne/.cache/pre-commit/patch1732066991-30975.
black....................................................................Passed
ruff.....................................................................Passed
typos....................................................................Failed
- hook id: typos
- exit code: 2

error: `aer` should be `are`
  --> tests/test_match_type.py:20:4
   |
20 | # 'aer banknote berlitz calloway centrust cluett fromstein '
   |    ^^^
   |

[INFO] Restored changes from /home/xnne/.cache/pre-commit/patch1732066991-30975.
```

It's my `_typos.toml`:

```toml
[files]
extend-exclude = [
    "tests/test_match_type.py"
]
```
