### ISSUE TITLE
[Feature Request] SARIF format support

### ISSUE THREAD

**Issue by Zxilly** [crate-ci/typos#1042] opened 2024-06-18 15:15 UTC
I'm reaching out with a feature request for `typos`. It'd be fantastic if we could add support for the SARIF format. 

For those who might not be familiar, SARIF is a JSON-based file format that's becoming a standard for sharing the results of static analysis tools. You can check out the spec here: [SARIF Specification](https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html).

One team member mentioned an expectation for this feature at https://github.com/crate-ci/typos/issues/1036, so I created this new issue in the hopes of tracking the development of this feature

**Comment by epage** [comment] 2024-06-18 18:47
This is a dupe of #594

**Closed by epage** 2024-06-18 18:47 UTC
