### ISSUE TITLE
github action is broken

### ISSUE THREAD

**Issue by halkeye** [crate-ci/typos#610] opened 2022-11-04 03:51 UTC
Looks like its drying to download https://github.com/crate-ci/typos/releases/download/v1.12.13/typos-v1.12.13-x86_64-unknown-linux-musl.tar.gz but that release isn't released (yet)

**Comment by halkeye** [comment] 2022-11-04 03:54
For future people, while the marketplace doesn't list it, you can use release tags

      `uses: crate-ci/typos@v1.12.12`

**Comment by bluekms** [comment] 2022-11-04 05:42
@halkeye thanks

**Comment by waldirborbajr** [comment] 2022-11-04 11:43
Facing the same problem... Thank you for workarround

**Comment by epage** [comment] 2022-11-04 14:56
A new release is being created: https://github.com/crate-ci/typos/actions/runs/3394776486

Our [release workflow](https://github.com/crate-ci/typos/blob/master/.github/workflows/post-release.yml) seems to run inconsistently.  The only common factor I can see for when it failed is when all crates are released.  Looking closer, I wonder if github is being confused between v1.12.13 and varcon-v0.6.5 as our push glob is `v*`.  I'll have to go and make that more specific in hopes that it hardens it.

**Comment by epage** [comment] 2023-01-14 03:13
Closing as I believe this is a duplicate of #590.  If not, we can always re-open

**Closed by epage** 2023-01-14 03:13 UTC
